
package:
    name: spark
    version: 1.1.0

source:
    git_url: https://github.com/apache/spark                                               # [linux]
    git_tag: v1.1.0                                                                        # [linux]
    fn: spark-1.1.0-bin-hadoop2.4.tgz                                                      # [osx]
    url: http://www.apache.org/dist/spark/spark-1.1.0/spark-1.1.0-bin-hadoop2.4.tgz        # [osx]
    md5: 97e496772878dfa14be102e190e366fc                                                  # [osx]

build:
    number: 0

requirements:
    build:
        - python
        - apache-maven  # [linux]
        - scala 2.10.*  # [linux]

    run:
        - python
        - apache-maven  # [linux]
        - py4j

test:
    imports:
        - pyspark

    commands:
        - pyspark --help

about:
    home: https://spark.apache.org/
    license: Apache 2.0 license
