package:
  name: ipython
  version: 2.2.0

source:
  fn: ipython-2.2.0.tar.gz
  url: https://pypi.python.org/packages/source/i/ipython/ipython-2.2.0.tar.gz
  md5: b91d3724f655a8e16d022772f696cfd5
  patches:
    - cprt.patch

build:
  entry_points:
    - ipython = IPython:start_ipython
    - pycolor = IPython.utils.PyColorize:main
    - ipcontroller = IPython.parallel.apps.ipcontrollerapp:launch_new_instance
    - ipengine = IPython.parallel.apps.ipengineapp:launch_new_instance
    - iplogger = IPython.parallel.apps.iploggerapp:launch_new_instance
    - ipcluster = IPython.parallel.apps.ipclusterapp:launch_new_instance
    - iptest = IPython.testing.iptestcontroller:main
    - irunner = IPython.lib.irunner:main
  number: 1                  [osx]
  osx_is_app: True

requirements:
  build:
    - python
    - setuptools             [win or py3k]
    - pyreadline             [win]
  run:
    - python
    - pyreadline             [win]
    - python.app             [osx]

test:
  commands:
    - ipython -h
  imports:
    - IPython

about:
  home: http://ipython.org/
  license: BSD
