
package:
    name: selenium-server-standalone
    version: 2.42.2

source:
    fn: selenium-server-standalone-2.42.2.jar
    url: http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
    md5: e357c6c0a757311b0da571abd7386cac

build:
    number: 0

about:
    home: http://www.seleniumhq.org/
    license: Apache License 2.0

