package:
  name: ipython-notebook
  version: 2.2.0

requirements:
  run:
    - python
    - ipython
    - pyzmq
    - tornado
    - jinja2

app:
  entry: ipython notebook                         [not osx]
  entry: open ${PREFIX}/bin/ipython_mac.command   [osx]
  icon: ipynb_icon_64x64.png
  summary: IPython Notebook

about:
  home: http://ipython.org/notebook.html
  license: BSD
